spring:
  application:
    name: kafka-inflight-proxy
  main:
    web-application-type: none

kafka-proxy:
  listen-address: "0.0.0.0:19092"
  upstream-broker-address: "kafka-1:9092"
  broker-proxy-addresses:
    "[kafka-1:9092]": "proxy-1:19092"
    "[kafka-2:9092]": "proxy-2:19092"
    "[kafka-3:9092]": "proxy-3:19092"
  protocol:
    max-frame-size-bytes: 104857600
  request-logging:
    enabled: false
    base-directory: "./logs/kafka-proxy"
