spring:
  application:
    name: kafka-inflight-proxy
  main:
    web-application-type: servlet

kafka-proxy:
  listen-address: "0.0.0.0:19092"
  upstream-broker-address: "localhost:9092"
  server:
    enabled: true
    connect-timeout-millis: 10000
  broker-proxy-addresses:
    "[localhost:9092]": "localhost:19092"
    "[localhost:9093]": "localhost:19093"
    "[localhost:9094]": "localhost:19094"
  protocol:
    max-frame-size-bytes: 104857600
    transformation-worker-threads: 8
    transformation-executor-queue-capacity: 1024
    per-connection-transformation-queue-capacity: 32
  request-logging:
    enabled: true
    base-directory: "./logs/kafka-proxy"
  crypto:
    key-encryption-key: "${KAFKA_PROXY_KEK}"
    encryption-key-header-name: "encryption-key"
    encryption-iv-header-name: "encryption-iv"
  redis:
    host: "localhost"
    port: 6379
    database: 0
    username: null
    password: null
    connect-timeout: 2s
    command-timeout: 2s
